env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/vue3-recommended'
  - airbnb
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
settings:
  import/resolver:
    typescript:
      project: "."
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
