env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - airbnb
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: module
settings:
  import/resolver:
    typescript:
      project: "./src"
plugins:
  - vue
  - '@typescript-eslint'
rules: 
  import/extensions: #importの時に拡張子要るで〜
    - error
    - never
    - js: never
      ts: never
